### PR TITLE
Fix breaking changes introduced by elm-aws-core pre-release-1.0.0 PR (wip)

### PR DESCRIPTION
**Pull request by ktonon**
Not ready to merge. Wait until I merge https://github.com/ktonon/elm-aws-core/pull/3

Fixes breaking changes. I may update this PR as I update the other.

### CODE REVIEW

**Comment by billstclair** [comment]
Thanks, Kevin. I'll look at this soon after you merge [ktonon/elm-aws-core#3](https://github.com/ktonon/elm-aws-core/pull/3). Not sure I'll get an email when you do that, so please comment here, so I know.

**Comment by billstclair** [comment]
I think the most recent changes to elm-aws-core may leave elm-s3 slightly broken, but it will be easier for me to fix if I merge this PR, so that's what I'm doing.

**Comment by billstclair** [comment]
Easy to fix. Works now with the latest elm-aws-core.

Thank you, Kevin!

**Comment by ktonon** [comment]
Nice. Glad it worked out. Just published `elm-aws-core` release 1.0.0 to the elm package repo

**Comment by billstclair** [comment]
I updated elm-s3 to use ktonon/elm-aws-core from the Elm repository instead of a git submodule. I also updated the API to separate creation of a Request from adding headers and queries and turning it into a signed request inside a Task.

I still have to fix an issue with mime types coming back from a standard HTTP request to an object written with elm-s3. I may need a change to elm-aws-core to use just an overridden content-type header without merging it with the default.

**Pull request merged**
